
export const ADD_TO_CART= 'ADD_TO_CART'
export const ADD_TO_CART_REQUEST= 'ADD_TO_CART_REQUEST'
export const REMOVE_ITEM_CART='REMOVE_ITEM_CART'
export const SAVE_SHIPPING_INFO='SAVE_SHIPPING_INFO'


